/**
 * lab2date seed — Phase 2 catalog data.
 *
 * Idempotent: re-running will upsert all rows by their stable slug/id.
 *
 * Counts:
 *  - 10 categories
 *  - ~25 brands
 *  - 6 supplier companies
 *  - 1 admin user + 6 sellers + 2 buyers
 *  - 60+ products distributed across categories/brands
 */

import { PrismaClient, ProductCondition, ProductMode, ProductStatus, UserRole } from '@prisma/client';

const prisma = new PrismaClient();

// ─── Categories ──────────────────────────────────────────────────────────────

const CATEGORIES = [
  { slug: 'general-lab',      name: 'General Laboratory',     description: 'Standard lab workhorses',            sortOrder: 0 },
  { slug: 'analytical',       name: 'Analytical Instruments', description: 'Spectrometers, HPLC, GC',            sortOrder: 1 },
  { slug: 'biotech',          name: 'Biotech & Life Sciences', description: 'PCR, sequencers, incubators',       sortOrder: 2 },
  { slug: 'microscopy',       name: 'Microscopy',              description: 'Optical, electron, confocal',       sortOrder: 3 },
  { slug: 'centrifugation',   name: 'Centrifugation',          description: 'Ultra, micro, refrigerated',        sortOrder: 4 },
  { slug: 'chromatography',   name: 'Chromatography',          description: 'HPLC, GC, IC, FPLC',                sortOrder: 5 },
  { slug: 'test-measurement', name: 'Test & Measurement',     description: 'Calibration, leak testing',         sortOrder: 6 },
  { slug: 'medical',          name: 'Medical Equipment',      description: 'Diagnostics & clinical',            sortOrder: 7 },
  { slug: 'process',          name: 'Process Equipment',      description: 'Bioreactors, boilers, pumps',       sortOrder: 8 },
  { slug: 'data-software',    name: 'Data & Software',        description: 'LIMS, ELN, data systems',           sortOrder: 9 },
];

// ─── Brands ──────────────────────────────────────────────────────────────────

const BRANDS = [
  { slug: 'beckman-coulter',  name: 'Beckman Coulter' },
  { slug: 'agilent',          name: 'Agilent Technologies' },
  { slug: 'carl-zeiss',       name: 'Carl Zeiss' },
  { slug: 'thermo-fisher',    name: 'Thermo Fisher Scientific' },
  { slug: 'bio-rad',          name: 'Bio-Rad' },
  { slug: 'eppendorf',        name: 'Eppendorf' },
  { slug: 'sartorius',        name: 'Sartorius' },
  { slug: 'waters',           name: 'Waters Corporation' },
  { slug: 'perkinelmer',      name: 'PerkinElmer' },
  { slug: 'tecan',            name: 'Tecan' },
  { slug: 'roche',            name: 'Roche' },
  { slug: 'illumina',         name: 'Illumina' },
  { slug: 'leica',            name: 'Leica Microsystems' },
  { slug: 'olympus',          name: 'Olympus' },
  { slug: 'nikon',            name: 'Nikon Instruments' },
  { slug: 'shimadzu',         name: 'Shimadzu' },
  { slug: 'mettler-toledo',   name: 'Mettler Toledo' },
  { slug: 'merck-millipore',  name: 'Merck Millipore' },
  { slug: 'ge-healthcare',    name: 'Cytiva (GE Healthcare)' },
  { slug: 'idexx',            name: 'IDEXX' },
  { slug: 'qiagen',           name: 'Qiagen' },
  { slug: 'molecular-devices', name: 'Molecular Devices' },
  { slug: 'horiba',           name: 'Horiba' },
  { slug: 'bruker',           name: 'Bruker' },
];

// ─── Companies (sellers' employers) ──────────────────────────────────────────

const COMPANIES = [
  { slug: 'biolab-refurb-gmbh', name: 'BioLab Refurb GmbH', country: 'Germany', website: 'https://biolab-refurb.example', description: 'Certified refurbished centrifuges, balances and bioreactors.', isVerified: true, isFeatured: true },
  { slug: 'northeast-scientific', name: 'Northeast Scientific', country: 'USA', website: 'https://northeast-scientific.example', description: 'Premium chromatography and mass spectrometry systems.', isVerified: true, isFeatured: true },
  { slug: 'optiscope-trade-bv', name: 'OptiScope Trade BV', country: 'Netherlands', website: 'https://optiscope.example', description: 'Microscopy specialists — Zeiss, Leica, Olympus, Nikon.', isVerified: true, isFeatured: true },
  { slug: 'pivot-park-instruments', name: 'Pivot Park Instruments', country: 'Netherlands', website: 'https://pivotpark.example', description: 'High-end analytical instruments for pharma R&D.', isVerified: true, isFeatured: true },
  { slug: 'eurolab-supplies', name: 'EuroLab Supplies', country: 'Belgium', website: 'https://eurolab.example', description: 'New OEM equipment from Sartorius, Eppendorf, Mettler.', isVerified: true, isFeatured: true },
  { slug: 'asia-scientific-direct', name: 'Asia Scientific Direct', country: 'Singapore', website: 'https://asci.example', description: 'Asia-Pacific sourcing for lab essentials.', isVerified: false, isFeatured: true },
];

// ─── Users (admin + sellers + buyers) ────────────────────────────────────────
//
// Stable IDs used because Better-Auth's Prisma adapter expects `id String @id`
// without an autogenerated default — seed must provide values.
// Real production users come from the auth flow; these are convenience records.

const ADMIN = {
  id: 'seed_user_admin',
  email: 'admin@lab2date.com',
  name: 'lab2date Admin',
  role: UserRole.ADMIN,
};

const SELLERS = [
  { id: 'seed_user_seller_biolab',       email: 'sales@biolab-refurb.example',    name: 'BioLab Sales Team',      companySlug: 'biolab-refurb-gmbh' },
  { id: 'seed_user_seller_northeast',    email: 'sales@northeast-scientific.ex',  name: 'Northeast Sales',         companySlug: 'northeast-scientific' },
  { id: 'seed_user_seller_optiscope',    email: 'sales@optiscope.example',        name: 'OptiScope Sales',         companySlug: 'optiscope-trade-bv' },
  { id: 'seed_user_seller_pivot',        email: 'sales@pivotpark.example',        name: 'Pivot Park Sales',        companySlug: 'pivot-park-instruments' },
  { id: 'seed_user_seller_eurolab',      email: 'sales@eurolab.example',          name: 'EuroLab Sales',           companySlug: 'eurolab-supplies' },
  { id: 'seed_user_seller_asia',         email: 'sales@asci.example',             name: 'Asia Scientific Sales',   companySlug: 'asia-scientific-direct' },
];

const BUYERS = [
  { id: 'seed_user_buyer_demo1', email: 'demo-buyer@lab2date.com', name: 'Demo Buyer' },
  { id: 'seed_user_buyer_demo2', email: 'researcher@lab2date.com', name: 'Demo Researcher' },
];

// ─── Products ────────────────────────────────────────────────────────────────
//
// Template-driven. Each row produces one Product upsert.

type Tpl = {
  brand: string;
  model: string;
  category: string;
  illustration: 'centrifuge' | 'microscope' | 'pcr' | 'hplc' | 'massspec' | 'balance';
  /** product subtype phrase appended to brand+model, e.g. "Refrigerated Centrifuge" */
  subtype: string;
  /** price in EUR cents; null = quote-only */
  priceCents: number | null;
  condition: ProductCondition;
  mode: ProductMode;
  year?: number;
  badge?: string;
  /** which company sells it (cycle if omitted) */
  company?: string;
  specs?: Record<string, string>;
  summary?: string;
};

const TEMPLATES: Tpl[] = [
  // ── Centrifugation (8) ────────────────────────────────────
  { brand: 'beckman-coulter', model: 'Allegra X-30R',         category: 'centrifugation', illustration: 'centrifuge', subtype: 'Refrigerated Benchtop Centrifuge', priceCents: 1280000, condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2019, badge: '15% off', company: 'biolab-refurb-gmbh',
    specs: { 'Max speed': '18,500 RPM', 'Max RCF': '30,074 × g', 'Max capacity': '4 × 1000 mL', 'Temperature range': '-10 °C to +40 °C' },
    summary: 'High-capacity refrigerated benchtop centrifuge with broad rotor selection.' },
  { brand: 'beckman-coulter', model: 'Avanti J-26 XPI',       category: 'centrifugation', illustration: 'centrifuge', subtype: 'High-Performance Centrifuge',     priceCents: 3950000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2020, company: 'biolab-refurb-gmbh',
    specs: { 'Max speed': '26,000 RPM', 'Max RCF': '82,000 × g', 'Capacity': '6 × 1000 mL', 'Brushless drive': 'Yes' } },
  { brand: 'beckman-coulter', model: 'Optima MAX-XP',         category: 'centrifugation', illustration: 'centrifuge', subtype: 'Tabletop Ultracentrifuge',        priceCents: 4280000, condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2018, badge: 'Premium', company: 'biolab-refurb-gmbh' },
  { brand: 'eppendorf',       model: '5810 R',                category: 'centrifugation', illustration: 'centrifuge', subtype: 'Refrigerated Multipurpose Centrifuge', priceCents: 480000, condition: 'REFURBISHED', mode: 'BUY_NOW', year: 2021, company: 'biolab-refurb-gmbh',
    specs: { 'Max speed': '14,000 RPM', 'Max RCF': '20,913 × g', 'Capacity': '4 × 750 mL' } },
  { brand: 'eppendorf',       model: '5424 R',                category: 'centrifugation', illustration: 'centrifuge', subtype: 'Refrigerated Microcentrifuge',    priceCents: 290000, condition: 'NEW',          mode: 'BUY_NOW',    year: 2025, badge: 'New', company: 'eurolab-supplies' },
  { brand: 'eppendorf',       model: '5430 R',                category: 'centrifugation', illustration: 'centrifuge', subtype: 'High-Speed Microcentrifuge',     priceCents: 380000, condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2022, company: 'biolab-refurb-gmbh' },
  { brand: 'thermo-fisher',   model: 'Sorvall LYNX 6000',     category: 'centrifugation', illustration: 'centrifuge', subtype: 'Superspeed Centrifuge',          priceCents: 4180000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2020, company: 'northeast-scientific' },
  { brand: 'thermo-fisher',   model: 'Sorvall ST 8',          category: 'centrifugation', illustration: 'centrifuge', subtype: 'Benchtop Centrifuge',            priceCents: 220000, condition: 'NEW',          mode: 'BUY_NOW',    year: 2025, company: 'eurolab-supplies' },

  // ── Chromatography (8) ────────────────────────────────────
  { brand: 'agilent',         model: '1260 Infinity II',      category: 'chromatography', illustration: 'hplc', subtype: 'Quaternary Pump LC System',           priceCents: 2890000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2020, company: 'northeast-scientific',
    specs: { 'Max pressure': '600 bar', 'Flow rate': '0.001 – 10 mL/min', 'Detectors': 'DAD, MWD, VWD' } },
  { brand: 'agilent',         model: '1290 Infinity II',      category: 'chromatography', illustration: 'hplc', subtype: 'UHPLC Binary System',                  priceCents: 4250000, condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2021, badge: 'Premium', company: 'northeast-scientific' },
  { brand: 'agilent',         model: '7890B GC',              category: 'chromatography', illustration: 'hplc', subtype: 'Gas Chromatograph',                  priceCents: 1850000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2019, company: 'northeast-scientific' },
  { brand: 'waters',          model: 'ACQUITY UPLC H-Class',  category: 'chromatography', illustration: 'hplc', subtype: 'PLUS System',                         priceCents: 3450000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2018, company: 'northeast-scientific' },
  { brand: 'waters',          model: 'ACQUITY UPLC I-Class',  category: 'chromatography', illustration: 'hplc', subtype: 'PLUS System',                         priceCents: 3950000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2020, company: 'northeast-scientific' },
  { brand: 'shimadzu',        model: 'Nexera X3',             category: 'chromatography', illustration: 'hplc', subtype: 'UHPLC System',                        priceCents: 3180000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2021, company: 'northeast-scientific' },
  { brand: 'thermo-fisher',   model: 'Vanquish Horizon',      category: 'chromatography', illustration: 'hplc', subtype: 'UHPLC System',                        priceCents: 3680000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2020, company: 'northeast-scientific' },
  { brand: 'ge-healthcare',   model: 'ÄKTA Pure 25',          category: 'chromatography', illustration: 'hplc', subtype: 'FPLC System',                         priceCents: 1280000, condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2019, company: 'biolab-refurb-gmbh' },

  // ── Microscopy (8) ────────────────────────────────────────
  { brand: 'carl-zeiss',      model: 'Axio Imager M2',        category: 'microscopy',    illustration: 'microscope', subtype: 'Upright Microscope',           priceCents: 1750000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2020, company: 'optiscope-trade-bv',
    specs: { 'Optics': 'Plan-Apochromat', 'Magnification': '1.25× – 100×', 'Illumination': 'LED + halogen' } },
  { brand: 'carl-zeiss',      model: 'LSM 980',               category: 'microscopy',    illustration: 'microscope', subtype: 'Confocal Laser Scanning',      priceCents: null,    condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2021, badge: 'Premium', company: 'optiscope-trade-bv' },
  { brand: 'carl-zeiss',      model: 'Axio Observer Z1',      category: 'microscopy',    illustration: 'microscope', subtype: 'Inverted Microscope',          priceCents: 2480000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2019, company: 'optiscope-trade-bv' },
  { brand: 'leica',           model: 'DM6 B',                 category: 'microscopy',    illustration: 'microscope', subtype: 'Upright Microscope',           priceCents: 1950000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2020, company: 'optiscope-trade-bv' },
  { brand: 'leica',           model: 'SP8 X',                 category: 'microscopy',    illustration: 'microscope', subtype: 'Confocal Microscope',          priceCents: null,    condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2019, company: 'optiscope-trade-bv' },
  { brand: 'olympus',         model: 'BX53',                  category: 'microscopy',    illustration: 'microscope', subtype: 'Clinical Upright Microscope',  priceCents: 980000,  condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2021, badge: '10% off', company: 'optiscope-trade-bv' },
  { brand: 'olympus',         model: 'CX23',                  category: 'microscopy',    illustration: 'microscope', subtype: 'Student Microscope',           priceCents: 89000,   condition: 'NEW',          mode: 'BUY_NOW',    year: 2025, badge: 'New', company: 'eurolab-supplies' },
  { brand: 'nikon',           model: 'Eclipse Ti2-E',         category: 'microscopy',    illustration: 'microscope', subtype: 'Inverted Microscope',          priceCents: 2280000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2020, company: 'optiscope-trade-bv' },

  // ── Analytical / Mass Spec (8) ────────────────────────────
  { brand: 'thermo-fisher',   model: 'Orbitrap Exploris 240', category: 'analytical',    illustration: 'massspec', subtype: 'High-Resolution Mass Spectrometer', priceCents: null, condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2021, badge: 'Premium', company: 'pivot-park-instruments' },
  { brand: 'thermo-fisher',   model: 'Q Exactive HF-X',       category: 'analytical',    illustration: 'massspec', subtype: 'Hybrid Quadrupole-Orbitrap',     priceCents: null,    condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2019, company: 'pivot-park-instruments' },
  { brand: 'waters',          model: 'Xevo TQ-S micro',       category: 'analytical',    illustration: 'massspec', subtype: 'Triple Quadrupole MS',           priceCents: 5680000, condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2020, company: 'pivot-park-instruments' },
  { brand: 'waters',          model: 'SYNAPT G2-Si',          category: 'analytical',    illustration: 'massspec', subtype: 'High-Definition MS',             priceCents: null,    condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2018, company: 'pivot-park-instruments' },
  { brand: 'agilent',         model: '6470 LC/TQ',            category: 'analytical',    illustration: 'massspec', subtype: 'Triple Quadrupole LC/MS',        priceCents: 4280000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2020, company: 'pivot-park-instruments' },
  { brand: 'agilent',         model: '5977B GC/MSD',          category: 'analytical',    illustration: 'massspec', subtype: 'GC/Mass Spec',                   priceCents: 2890000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2019, company: 'pivot-park-instruments' },
  { brand: 'perkinelmer',     model: 'NexION 5000',           category: 'analytical',    illustration: 'massspec', subtype: 'Multi-Quad ICP-MS',              priceCents: 3580000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2021, company: 'pivot-park-instruments' },
  { brand: 'bruker',          model: 'timsTOF Pro 2',         category: 'analytical',    illustration: 'massspec', subtype: 'Trapped Ion Mobility MS',        priceCents: null,    condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2022, badge: 'Premium', company: 'pivot-park-instruments' },

  // ── Biotech (PCR, sequencers, incubators) (10) ────────────
  { brand: 'bio-rad',         model: 'CFX96 Touch',           category: 'biotech',       illustration: 'pcr', subtype: 'Real-Time PCR Detection System',    priceCents: 850000,  condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2021, company: 'biolab-refurb-gmbh',
    specs: { 'Sample format': '96-well', 'Channels': '5 + FRET', 'Temperature accuracy': '±0.2 °C' } },
  { brand: 'bio-rad',         model: 'CFX384 Touch',          category: 'biotech',       illustration: 'pcr', subtype: 'Real-Time PCR System',              priceCents: 1180000, condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2020, company: 'biolab-refurb-gmbh' },
  { brand: 'bio-rad',         model: 'T100',                  category: 'biotech',       illustration: 'pcr', subtype: 'Thermal Cycler',                    priceCents: 280000,  condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2022, company: 'biolab-refurb-gmbh' },
  { brand: 'eppendorf',       model: 'Mastercycler Nexus',    category: 'biotech',       illustration: 'pcr', subtype: 'Gradient Thermocycler',             priceCents: 690000,  condition: 'NEW',          mode: 'BUY_NOW',    year: 2025, badge: 'New', company: 'eurolab-supplies' },
  { brand: 'eppendorf',       model: 'Mastercycler X40',      category: 'biotech',       illustration: 'pcr', subtype: 'High-Throughput Thermocycler',     priceCents: 980000,  condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2021, company: 'biolab-refurb-gmbh' },
  { brand: 'thermo-fisher',   model: 'ProFlex 96-well',       category: 'biotech',       illustration: 'pcr', subtype: 'PCR System',                        priceCents: 580000,  condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2020, company: 'biolab-refurb-gmbh' },
  { brand: 'roche',           model: 'LightCycler 480 II',    category: 'biotech',       illustration: 'pcr', subtype: 'qPCR System',                       priceCents: 1480000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2019, company: 'biolab-refurb-gmbh' },
  { brand: 'illumina',        model: 'NextSeq 550',           category: 'biotech',       illustration: 'pcr', subtype: 'Sequencing System',                 priceCents: 9850000, condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2020, badge: 'Premium', company: 'pivot-park-instruments' },
  { brand: 'illumina',        model: 'MiSeq',                 category: 'biotech',       illustration: 'pcr', subtype: 'Benchtop Sequencer',                priceCents: 4280000, condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2019, company: 'pivot-park-instruments' },
  { brand: 'qiagen',          model: 'QIAcube Connect',       category: 'biotech',       illustration: 'pcr', subtype: 'Automated Nucleic Acid Extraction', priceCents: 1280000, condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2021, company: 'biolab-refurb-gmbh' },

  // ── General Laboratory / Balances (8) ─────────────────────
  { brand: 'sartorius',       model: 'Cubis II',              category: 'general-lab',   illustration: 'balance', subtype: 'Premium Analytical Balance',     priceCents: 420000,  condition: 'NEW',          mode: 'BUY_NOW',    year: 2025, badge: 'New', company: 'eurolab-supplies',
    specs: { 'Capacity': '220 g', 'Readability': '0.0001 g', 'Repeatability': '0.00007 g' } },
  { brand: 'sartorius',       model: 'Practum 224',           category: 'general-lab',   illustration: 'balance', subtype: 'Analytical Balance',             priceCents: 180000,  condition: 'NEW',          mode: 'BUY_NOW',    year: 2025, company: 'eurolab-supplies' },
  { brand: 'mettler-toledo',  model: 'XPR226DR',              category: 'general-lab',   illustration: 'balance', subtype: 'Analytical Balance',             priceCents: 480000,  condition: 'NEW',          mode: 'BUY_NOW',    year: 2025, badge: 'New', company: 'eurolab-supplies' },
  { brand: 'mettler-toledo',  model: 'XS205 DualRange',       category: 'general-lab',   illustration: 'balance', subtype: 'Analytical Balance',             priceCents: 280000,  condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2022, company: 'biolab-refurb-gmbh' },
  { brand: 'sartorius',       model: 'Quintix 224-1S',        category: 'general-lab',   illustration: 'balance', subtype: 'Semi-Micro Balance',             priceCents: 320000,  condition: 'NEW',          mode: 'BUY_NOW',    year: 2025, company: 'eurolab-supplies' },
  { brand: 'mettler-toledo',  model: 'XP205',                 category: 'general-lab',   illustration: 'balance', subtype: 'Precision Balance',              priceCents: 220000,  condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2021, company: 'biolab-refurb-gmbh' },
  { brand: 'sartorius',       model: 'Entris II',             category: 'general-lab',   illustration: 'balance', subtype: 'Analytical Balance',             priceCents: 145000,  condition: 'NEW',          mode: 'BUY_NOW',    year: 2025, company: 'asia-scientific-direct' },
  { brand: 'mettler-toledo',  model: 'MS204TS',               category: 'general-lab',   illustration: 'balance', subtype: 'Analytical Balance',             priceCents: 195000,  condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2022, company: 'biolab-refurb-gmbh' },

  // ── Medical (4) ───────────────────────────────────────────
  { brand: 'idexx',           model: 'ProCyte Dx',            category: 'medical',       illustration: 'balance', subtype: 'Hematology Analyzer',            priceCents: 1180000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2020, company: 'asia-scientific-direct' },
  { brand: 'roche',           model: 'cobas c 311',           category: 'medical',       illustration: 'massspec', subtype: 'Clinical Chemistry Analyzer',   priceCents: null,    condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2018, company: 'asia-scientific-direct' },
  { brand: 'perkinelmer',     model: 'AAanalyst 400',         category: 'medical',       illustration: 'massspec', subtype: 'Atomic Absorption Spectrometer', priceCents: 980000, condition: 'REFURBISHED', mode: 'BUY_NOW',    year: 2019, company: 'northeast-scientific' },
  { brand: 'tecan',           model: 'Spark 10M',             category: 'medical',       illustration: 'balance', subtype: 'Multimode Microplate Reader',    priceCents: 1380000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2021, company: 'biolab-refurb-gmbh' },

  // ── Test & Measurement (3) ────────────────────────────────
  { brand: 'horiba',          model: 'Partica LA-960',        category: 'test-measurement', illustration: 'massspec', subtype: 'Laser Particle Size Analyzer', priceCents: 1850000, condition: 'REFURBISHED', mode: 'HYBRID',  year: 2020, company: 'northeast-scientific' },
  { brand: 'agilent',         model: 'Cary 5000',             category: 'test-measurement', illustration: 'massspec', subtype: 'UV-Vis-NIR Spectrophotometer', priceCents: 1280000, condition: 'REFURBISHED', mode: 'HYBRID', year: 2021, company: 'northeast-scientific' },
  { brand: 'shimadzu',        model: 'IRSpirit',              category: 'test-measurement', illustration: 'massspec', subtype: 'FTIR Spectrometer',           priceCents: 620000,  condition: 'NEW',         mode: 'BUY_NOW',  year: 2025, company: 'eurolab-supplies' },

  // ── Process (3) ───────────────────────────────────────────
  { brand: 'sartorius',       model: 'BIOSTAT B-DCU II',      category: 'process',       illustration: 'balance', subtype: 'Bench-Top Bioreactor',           priceCents: 3850000, condition: 'REFURBISHED', mode: 'HYBRID',     year: 2020, company: 'biolab-refurb-gmbh' },
  { brand: 'sartorius',       model: 'ambr 250',              category: 'process',       illustration: 'balance', subtype: 'High-Throughput Bioreactor',     priceCents: null,    condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2021, badge: 'Premium', company: 'pivot-park-instruments' },
  { brand: 'merck-millipore', model: 'Mobius 200L',           category: 'process',       illustration: 'balance', subtype: 'Single-Use Bioreactor',          priceCents: null,    condition: 'REFURBISHED', mode: 'QUOTE_ONLY', year: 2020, company: 'pivot-park-instruments' },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

// ─── Run ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('🌱 Seeding lab2date...');

  // Categories
  console.log('  · upserting categories');
  for (const c of CATEGORIES) {
    await prisma.category.upsert({
      where: { slug: c.slug },
      update: { name: c.name, description: c.description, sortOrder: c.sortOrder },
      create: c,
    });
  }

  // Brands
  console.log('  · upserting brands');
  for (const b of BRANDS) {
    await prisma.brand.upsert({
      where: { slug: b.slug },
      update: { name: b.name },
      create: b,
    });
  }

  // Companies
  console.log('  · upserting companies');
  for (const co of COMPANIES) {
    await prisma.company.upsert({
      where: { slug: co.slug },
      update: { name: co.name, country: co.country, website: co.website, description: co.description, isVerified: co.isVerified, isFeatured: co.isFeatured },
      create: co,
    });
  }

  // Map slug → id for FK linkage
  const categoryBySlug = Object.fromEntries(
    (await prisma.category.findMany()).map((c) => [c.slug, c.id]),
  );
  const brandBySlug = Object.fromEntries(
    (await prisma.brand.findMany()).map((b) => [b.slug, b.id]),
  );
  const companyBySlug = Object.fromEntries(
    (await prisma.company.findMany()).map((c) => [c.slug, c.id]),
  );

  // Users — admin
  console.log('  · upserting admin');
  await prisma.user.upsert({
    where: { id: ADMIN.id },
    update: { email: ADMIN.email, name: ADMIN.name, role: ADMIN.role },
    create: ADMIN,
  });

  // Users — sellers (with company linkage)
  console.log('  · upserting sellers');
  for (const s of SELLERS) {
    const companyId = companyBySlug[s.companySlug];
    await prisma.user.upsert({
      where: { id: s.id },
      update: { email: s.email, name: s.name, role: UserRole.SELLER, companyId },
      create: { id: s.id, email: s.email, name: s.name, role: UserRole.SELLER, companyId },
    });
  }

  // Buyers (no company)
  for (const b of BUYERS) {
    await prisma.user.upsert({
      where: { id: b.id },
      update: { email: b.email, name: b.name, role: UserRole.BUYER },
      create: { id: b.id, email: b.email, name: b.name, role: UserRole.BUYER },
    });
  }

  // Build company → sellerId map (one seller per company in seed)
  const sellerByCompany: Record<string, string> = Object.fromEntries(
    SELLERS.map((s) => [s.companySlug, s.id]),
  );

  // Products
  console.log(`  · upserting ${TEMPLATES.length} products`);
  for (const t of TEMPLATES) {
    const brandName = BRANDS.find((b) => b.slug === t.brand)?.name ?? t.brand;
    const title = `${brandName} ${t.model} ${t.subtype}`;
    const slug = slugify(`${t.brand}-${t.model}-${t.subtype}`).slice(0, 90);

    const companySlug = t.company ?? 'biolab-refurb-gmbh';
    const sellerId = sellerByCompany[companySlug];
    const companyId = companyBySlug[companySlug];
    const categoryId = categoryBySlug[t.category];
    const brandId = brandBySlug[t.brand];

    if (!sellerId || !categoryId) {
      console.warn(`  ! skipping ${title}: missing seller or category`);
      continue;
    }

    await prisma.product.upsert({
      where: { slug },
      update: {
        title,
        condition: t.condition,
        mode: t.mode,
        status: ProductStatus.PUBLISHED,
        priceCents: t.priceCents,
        currency: 'EUR',
        yearMade: t.year,
        specs: t.specs ?? undefined,
        summary: t.summary ?? `${brandName} ${t.model} — ${t.subtype.toLowerCase()}.`,
        illustration: t.illustration,
        categoryId,
        brandId,
        sellerId,
        companyId,
      },
      create: {
        slug,
        title,
        condition: t.condition,
        mode: t.mode,
        status: ProductStatus.PUBLISHED,
        priceCents: t.priceCents,
        currency: 'EUR',
        yearMade: t.year,
        specs: t.specs ?? undefined,
        summary: t.summary ?? `${brandName} ${t.model} — ${t.subtype.toLowerCase()}.`,
        images: [],
        illustration: t.illustration,
        categoryId,
        brandId,
        sellerId,
        companyId,
      },
    });
  }

  const counts = {
    categories: await prisma.category.count(),
    brands: await prisma.brand.count(),
    companies: await prisma.company.count(),
    users: await prisma.user.count(),
    products: await prisma.product.count(),
  };
  console.log('✅ Done.', counts);
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
